// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH5FwtgC8u9npsoshSmbFiTZkIyKLW_ZE',
    appId: '1:108192911134:web:85be7112d90b9be6a1c30f',
    messagingSenderId: '108192911134',
    projectId: 'bayt-c76f3',
    authDomain: 'bayt-c76f3.firebaseapp.com',
    storageBucket: 'bayt-c76f3.appspot.com',
    measurementId: 'G-W7HRXGPHR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRAue_6l8e3JU9HJn7lwwt1DPvMO5UWhE',
    appId: '1:108192911134:android:cfc59a368fe61336a1c30f',
    messagingSenderId: '108192911134',
    projectId: 'bayt-c76f3',
    storageBucket: 'bayt-c76f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7xHKzOpFapd2boy5fj2i1RBc8KuTVOI',
    appId: '1:108192911134:ios:43f316eca5095115a1c30f',
    messagingSenderId: '108192911134',
    projectId: 'bayt-c76f3',
    storageBucket: 'bayt-c76f3.appspot.com',
    iosClientId: '108192911134-ss5o8bnlseictia8okpjr420r3j236p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.byatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx7xHKzOpFapd2boy5fj2i1RBc8KuTVOI',
    appId: '1:108192911134:ios:43f316eca5095115a1c30f',
    messagingSenderId: '108192911134',
    projectId: 'bayt-c76f3',
    storageBucket: 'bayt-c76f3.appspot.com',
    iosClientId: '108192911134-ss5o8bnlseictia8okpjr420r3j236p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.byatFlutter',
  );
}
